# This is a basic workflow to help you get started with Actions

name: MATLAB test on GitHub-Hosted Runner

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  aa_test:
    name: Minimum test using SPM and FSL only
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 51200
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Check out repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v2

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          # MATLAB release to set up R2020a
          release: R2020a

      - name: Install tools under $HOME/tools
        run: |
          sudo apt-get update
          sudo apt-get install awscli
          mkdir $HOME/tools
          git clone https://github.com/spm/spm12 $HOME/tools/spm12
          wget -P $HOME/tools http://fsl.fmrib.ox.ac.uk/fsldownloads/fsl-6.0.5-centos7_64.tar.gz
          cd $HOME/tools
          tar xzf fsl-6.0.5-centos7_64.tar.gz
          rm fsl-6.0.5-centos7_64.tar.gz
          mkdir $HOME/tools/config
          cp $GITHUB_WORKSPACE/.github/workflows/fsl_bash $HOME/tools/config
          source $HOME/tools/config/fsl_bash

      - name: Retrive test data under $HOME/data/aa_demo
        run: |
          mkdir $HOME/data
          mkdir $HOME/data/aa_demo
          aws s3 cp s3://openneuro.org/ds000114 $HOME/data/aa_demo/ds000114 --recursive --exclude "*" --include "task-*" --no-sign-request
          aws s3 cp s3://openneuro.org/ds000114 $HOME/data/aa_demo/ds000114 --recursive --exclude "*" --include "dwi*" --no-sign-request
          aws s3 cp s3://openneuro.org/ds000114/sub-01 $HOME/data/aa_demo/ds000114/sub-01 --recursive --no-sign-request
          aws s3 cp s3://openneuro.org/ds000114/sub-02 $HOME/data/aa_demo/ds000114/sub-02 --recursive --no-sign-request
          aws s3 cp s3://openneuro.org/ds000114/sub-03 $HOME/data/aa_demo/ds000114/sub-03 --recursive --no-sign-request
          aws s3 cp s3://openneuro.org/ds000114/sub-04 $HOME/data/aa_demo/ds000114/sub-04 --recursive --no-sign-request
          aws s3 cp s3://openneuro.org/ds000114/sub-05 $HOME/data/aa_demo/ds000114/sub-05 --recursive --no-sign-request
          aws s3 cp s3://openneuro.org/ds002737/sub-01/ses-03 $HOME/data/aa_demo/ds002737/sub-01/ses-03 --recursive --no-sign-request
          ls $HOME/data/aa_demo
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true

      - name: Configure aa
        run: |
          echo "Free space:"
          df -h
          echo $FSLDIR
          mkdir $HOME/.aa
          cp $GITHUB_WORKSPACE/.github/workflows/aap_parameters_defaults_GitHub.xml $HOME/.aa/aap_parameters_user.xml
          mkdir $HOME/projects

      - name: Run script
        uses: matlab-actions/run-command@v1
        with:
          command: addpath(getenv('GITHUB_WORKSPACE')), aa_ver5, SPM = spmClass(fullfile(getenv('HOME'),'tools','spm12')), SPM.load, aa_test
