# This is a basic workflow to help you get started with Actions

name: MATLAB test on GitHub-Hosted Runner

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  aa_test:
    name: Minimum test using SPM only
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          # MATLAB release to set up R2020a
          release: R2020a

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install awscli
          mkdir $GITHUB_WORKSPACE/tools
          git clone https://github.com/spm/spm12 $GITHUB_WORKSPACE/tools/spm12
          ls $GITHUB_WORKSPACE/tools

      - name: Retrive test data
        run: |
          mkdir $GITHUB_WORKSPACE/data
          aws s3 cp s3://openneuro.org/ds000114 $GITHUB_WORKSPACE/data/ds000114 --recursive --exclude "*" --include "task-*" --no-sign-request
          aws s3 cp s3://openneuro.org/ds000114 $GITHUB_WORKSPACE/data/ds000114 --recursive --exclude "*" --include "dwi*" --no-sign-request
          aws s3 cp s3://openneuro.org/ds000114/sub-01 $GITHUB_WORKSPACE/data/ds000114/sub-01 --recursive --no-sign-request
          aws s3 cp s3://openneuro.org/ds000114/sub-02 $GITHUB_WORKSPACE/data/ds000114/sub-02 --recursive --no-sign-request
          aws s3 cp s3://openneuro.org/ds000114/sub-03 $GITHUB_WORKSPACE/data/ds000114/sub-03 --recursive --no-sign-request
          aws s3 cp s3://openneuro.org/ds000114/sub-04 $GITHUB_WORKSPACE/data/ds000114/sub-04 --recursive --no-sign-request
          aws s3 cp s3://openneuro.org/ds000114/sub-05 $GITHUB_WORKSPACE/data/ds000114/sub-05 --recursive --no-sign-request
          aws s3 cp s3://openneuro.org/ds002737/sub-01/ses-03 $GITHUB_WORKSPACE/data/ds002737/sub-01/ses-03 --recursive --no-sign-request
          ls $GITHUB_WORKSPACE/data
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true

#- name: Run script
      #  uses: matlab-actions/run-command@v1
      #  with:
      #    command: aa_ver5, aa_test
